; Script generated by ChatGPT for Inventory Management App

[Setup]
AppName=Inventory Management System
AppVersion=1.0
DefaultDirName={pf}\InventoryApp
DefaultGroupName=InventoryApp
OutputDir=dist
OutputBaseFilename=InventoryAppInstaller
Compression=lzma
SolidCompression=yes

[Files]
Source: "build\exe.win-amd64-3.13\*"; DestDir: "{app}"; Flags: recursesubdirs

[Icons]
Name: "{group}\Inventory App"; Filename: "{app}\run_app.exe"
Name: "{group}\Uninstall Inventory App"; Filename: "{uninstallexe}"

